### ISSUE TITLE
[Craftify (based on Elementa)] Elementa crashes after a while of leaving the game open, killing the Craftify GUI.

### ISSUE THREAD

**Issue by TheoCGaming** [EssentialGG/Elementa#120]
**Describe the bug**

**To Reproduce**
1. Run minecraft with Craftify (a music control mod)
2. Join a world and set up Craftify using /craftify (Documentation [here](https://github.com/ThatGravyBoat/Craftify#readme))
3. Leave the game open and idle for who knows how long
4. You'll get a message in chat and a ton of spam in the logs, and the "now playing" area will stop rendering.

**Expected behavior**
Leaving the game open doesn't cause any errors

**Additional context**

System: Arch Linux (6.4.4-zen1-1-zen)
Java version: 17
Minecraft: 1.20.1
Elementa version: *integrated as a child mod, unknown*

Log: 
```
[13:14:36] [Render thread/INFO]: Game entered main loop!   <-- Game officially started

...    over 4 hours later of various logs from other mods and the main game...

[17:35:23] [Render thread/INFO]: [STDOUT]: Elementa: Cyclic constraint structure detected!
[17:35:23] [Render thread/INFO]: [STDOUT]: If you are a developer, set the environment variable "elementa.dev=true" to assist in debugging the issue.
[17:35:23] [Render thread/INFO]: [STDOUT]: Gui name: class_433
[17:35:23] [Render thread/INFO]: [STDERR]: java.lang.StackOverflowError
[17:35:23] [Render thread/INFO]: [STDERR]: 	at gg.essential.elementa.constraints.RelativeConstraint.getWidthImpl(RelativeConstraint.kt:38)
[17:35:23] [Render thread/INFO]: [STDERR]: 	at gg.essential.elementa.constraints.WidthConstraint.getWidth(Constraint.kt:138)
[17:35:23] [Render thread/INFO]: [STDERR]: 	at gg.essential.elementa.constraints.animation.WidthAnimationComponent.getWidthImpl(AnimationComponent.kt:163)
[17:35:23] [Render thread/INFO]: [STDERR]: 	at gg.essential.elementa.constraints.WidthConstraint.getWidth(Constraint.kt:138)
[17:35:23] [Render thread/INFO]: [STDERR]: 	at gg.essential.elementa.constraints.animation.WidthAnimationComponent.getWidthImpl(AnimationComponent.kt:163)

...    Continues for thousands of lines

[17:35:23] [Render thread/INFO]: [STDERR]: 	at gg.essential.elementa.constraints.animation.WidthAnimationComponent.getWidthImpl(AnimationComponent.kt:163)
[17:35:23] [Render thread/INFO]: [STDERR]: 	at gg.essential.elementa.constraints.WidthConstraint.getWidth(Constraint.kt:138)
[17:35:23] [Render thread/INFO]: [STDERR]: 	at gg.essential.elementa.constraints.animation.WidthAnimationComponent.getWidthImpl(AnimationComponent.kt:163)
[17:35:23] [Render thread/INFO]: [STDERR]: 	at gg.essential.elementa.constraints.WidthConstraint.getWidth(Constraint.kt:138)
[17:35:23] [Render thread/INFO]: [CHAT] §cElementa encountered an error while drawing a GUI. Check your logs for more information.
[17:35:23] [DefaultDispatcher-worker-6/ERROR]: Uncaught exception in thread "DefaultDispatcher-worker-6"
java.lang.StackOverflowError: null
	at gg.essential.elementa.constraints.WidthConstraint.getWidth(Constraint.kt:138) ~[elementa-590-c4250c8341948a4b.jar:?]
	at gg.essential.elementa.constraints.animation.WidthAnimationComponent.getWidthImpl(AnimationComponent.kt:163) ~[elementa-590-c4250c8341948a4b.jar:?]
	at gg.essential.elementa.constraints.WidthConstraint.getWidth(Constraint.kt:138) ~[elementa-590-c4250c8341948a4b.jar:?]
	at gg.essential.elementa.constraints.animation.WidthAnimationComponent.getWidthImpl(AnimationComponent.kt:163) ~[elementa-590-c4250c8341948a4b.jar:?]

...    more log spam

	at gg.essential.elementa.constraints.animation.WidthAnimationComponent.getWidthImpl(AnimationComponent.kt:163) ~[elementa-590-c4250c8341948a4b.jar:?]
	at gg.essential.elementa.constraints.WidthConstraint.getWidth(Constraint.kt:138) ~[elementa-590-c4250c8341948a4b.jar:?]
	at gg.essential.elementa.constraints.animation.WidthAnimationComponent.getWidthImpl(AnimationComponent.kt:163) ~[elementa-590-c4250c8341948a4b.jar:?]
	at gg.essential.elementa.constraints.WidthConstraint.getWidth(Constraint.kt:138) ~[elementa-590-c4250c8341948a4b.jar:?]
	at gg.essential.elementa.constraints.animation.WidthAnimationComponent.getWidthImpl(AnimationComponent.kt:163) ~[elementa-590-c4250c8341948a4b.jar:?]
[17:37:48] [Render thread/INFO]: [CHAT] [Rank]Multiplayerplayer1: Ill give someone a stack of emeralds for feather falling 4
[17:37:59] [Render thread/INFO]: [CHAT] [Rank]Multiplayerplayer2: ive got one
[17:38:21] [Render thread/INFO]: [CHAT] [Rank]Multiplayerplayer1: Bet
```

**Comment by Sychic** [comment]
Could you attach a full log? Missing parts of the stacktrace makes this much harder to diagnose.

**Comment by TheoCGaming** [comment]
I'll see if I can reproduce this in singleplayer so I can get a cleaner log.

**Comment by Sychic** [comment]
Shouldn't matter, just give me the full log.

**Comment by TheoCGaming** [comment]
https://mclo.gs/QuviAs0
the log is about 1 mb in size

**Comment by Sychic** [comment]
Hm, just from the logs I can't really see any apparent issues. Which part of the player exactly breaks? Can you attach a screenshot?

**Comment by TheoCGaming** [comment]
The music controller stops rendering
![image](https://github.com/EssentialGG/Elementa/assets/65421262/1d7f7bda-de5e-4363-aaf7-080f57b9e694)
to...
![image](https://github.com/EssentialGG/Elementa/assets/65421262/731843fe-aea3-4fa3-aad1-fca593622770)
(simulated)

**Comment by TheoCGaming** [comment]
> Hm, just from the logs I can't really see any apparent issues. Which part of the player exactly breaks? Can you attach a screenshot?

also don't forget the log spam in the middle

**Comment by DJtheRedstoner** [comment]
This is not a place to report issues with individual mods that use Elementa, this should be reported to Craftify. If this was caused by a bug/regression in Elementa, then that can be reported here in a new issue.

**Comment by TheoCGaming** [comment]
hooray this back-and-forth again

https://github.com/ThatGravyBoat/Craftify/issues/69

![image](https://github.com/EssentialGG/Elementa/assets/65421262/508c42b5-68d8-45f2-901c-3e092fc4c134)

why must this be so common

**Comment by TheoCGaming** [comment]
i take the bug to the mod dev
"solely an elementa issue"
i take the bug to elementa devs
"report it to craftify"
this is honestly annoying

**Comment by DJtheRedstoner** [comment]
If you want to avoid back and forth, explain why you created this issue here rather than just making what is seemingly a support request. Regardless, this is a technical issue tracker and we generally do not have the capacity to evaluate an issue without a simple reproducer.

**Comment by Sychic** [comment]
Additionally, this is likely some kind of implementation issue on their end due to how it doesn't occur with other uses of elementa.
